import type {
  AgentDiscoveryV1,
  AgentOverviewV1,
  AgentPipelinesV1,
  AgentSchedulesV1,
  AgentTriggersV1,
  AutopilotConnectManifestV1,
  InstallationHealthV1,
} from "./contracts";

/** Generic public-only response fixtures for Flight Deck compatibility tests. */
export const controlPlaneV1Fixtures = {
  manifest: {
    kind: "wingman_autopilot_connect",
    version: 1,
    generated_at: "2026-01-01T00:00:00.000Z",
    installation: {
      id: "autopilot_0123456789abcdef0123456789abcdef",
      npub: `npub1${"q".repeat(58)}`,
    },
    endpoints: {
      fips: `http://npub1${"q".repeat(58)}.fips:3601`,
      https: "https://autopilot.example",
    },
    api: {
      version: 1,
      capabilities: [
        "health",
        "agents.read",
        "agents.overview.read",
        "agents.pipelines.read",
        "agents.schedules.read",
        "agents.triggers.read",
      ],
      health_path: `/api/owners/npub1${"p".repeat(58)}/control-plane/v1/health`,
      agents_path: `/api/owners/npub1${"p".repeat(58)}/control-plane/v1/agents`,
    },
  } satisfies AutopilotConnectManifestV1,
  health: {
    ok: true,
    installation_id: "autopilot_0123456789abcdef0123456789abcdef",
    installation_npub: `npub1${"q".repeat(58)}`,
    api_version: 1,
  } satisfies InstallationHealthV1,
  discovery: {
    installation_id: "autopilot_0123456789abcdef0123456789abcdef",
    agents: [{
      agent_id: "agent-example",
      bot_npub: `npub1${"x".repeat(58)}`,
      name: "Example Agent",
      description: "Product-neutral fixture",
      can_instruct: true,
      paths: {
        overview: `/api/owners/npub1${"p".repeat(58)}/control-plane/v1/agents/agent-example/overview`,
        pipelines: `/api/owners/npub1${"p".repeat(58)}/control-plane/v1/agents/agent-example/pipelines`,
        schedules: `/api/owners/npub1${"p".repeat(58)}/control-plane/v1/agents/agent-example/schedules`,
        triggers: `/api/owners/npub1${"p".repeat(58)}/control-plane/v1/agents/agent-example/triggers`,
      },
    }],
  } satisfies AgentDiscoveryV1,
  overview: {
    installation_id: "autopilot_0123456789abcdef0123456789abcdef",
    agent: {
      agent_id: "agent-example",
      bot_npub: `npub1${"x".repeat(58)}`,
      name: "Example Agent",
      description: "Product-neutral fixture",
      can_instruct: true,
      paths: {
        overview: `/api/owners/npub1${"p".repeat(58)}/control-plane/v1/agents/agent-example/overview`,
        pipelines: `/api/owners/npub1${"p".repeat(58)}/control-plane/v1/agents/agent-example/pipelines`,
        schedules: `/api/owners/npub1${"p".repeat(58)}/control-plane/v1/agents/agent-example/schedules`,
        triggers: `/api/owners/npub1${"p".repeat(58)}/control-plane/v1/agents/agent-example/triggers`,
      },
      picture: null,
      nip05: null,
      capabilities: ["chat_intercept"],
      enabled: true,
      archived: false,
    },
  } satisfies AgentOverviewV1,
  pipelines: {
    installation_id: "autopilot_0123456789abcdef0123456789abcdef",
    agent_id: "agent-example",
    bot_npub: `npub1${"x".repeat(58)}`,
    availability_mode: "explicit",
    default_mode: "explicit",
    available_definitions: [{
      pipeline_definition_id: "shared:0123456789ab",
      name: "Example pipeline",
      description: "Reusable library definition",
      scope: "shared",
      version: 2,
      tags: ["example"],
    }],
    assignments: [{ pipeline_definition_id: "shared:0123456789ab" }],
    defaults: [{ pipeline_definition_id: "shared:0123456789ab" }],
    overrides: [{ kind: "channel", context_id: "channel-example", pipeline_definition_id: "shared:0123456789ab" }],
    missing_definition_ids: [],
  } satisfies AgentPipelinesV1,
  schedules: {
    installation_id: "autopilot_0123456789abcdef0123456789abcdef",
    agent_id: "agent-example",
    bot_npub: `npub1${"x".repeat(58)}`,
    schedules: [{
      schedule_id: "schedule-example",
      agent_id: "agent-example",
      bot_npub: `npub1${"x".repeat(58)}`,
      name: "Daily review",
      enabled: true,
      cron_expression: "0 9 * * *",
      timezone: "Australia/Perth",
      active_start_time: null,
      active_end_time: null,
      action_type: "pipeline",
      pipeline_definition_id: "shared:0123456789ab",
      last_run_at: null,
      next_run_at: "2026-01-02T01:00:00.000Z",
    }],
  } satisfies AgentSchedulesV1,
  triggers: {
    installation_id: "autopilot_0123456789abcdef0123456789abcdef",
    agent_id: "agent-example",
    bot_npub: `npub1${"x".repeat(58)}`,
    triggers: [{
      trigger_id: "trigger-example",
      agent_id: "agent-example",
      bot_npub: `npub1${"x".repeat(58)}`,
      name: "Inbox watcher",
      enabled: true,
      trigger_type: "file_watcher",
      file_pattern: "*.json",
      action_type: "pipeline",
      pipeline_definition_id: "shared:0123456789ab",
      last_run_at: null,
    }],
  } satisfies AgentTriggersV1,
} as const;
